# Generated by Django 3.1.4 on 2020-12-29 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=6, unique=True)),
                ('companyName', models.CharField(max_length=50)),
                ('companyAddress', models.CharField(max_length=100)),
                ('companyCity', models.CharField(max_length=50)),
                ('companyState', models.CharField(max_length=50)),
                ('companyPostCode', models.CharField(max_length=5)),
                ('companyCountry', models.CharField(max_length=50)),
                ('invoiceDescription', models.TextField()),
                ('invoiceTotal', models.DecimalField(decimal_places=3, max_digits=20)),
                ('paymentAccount', models.CharField(blank=True, max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
