# Generated by Django 3.1.4 on 2020-12-30 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_app', '0002_invoice_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoiceDescription',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='companyState',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoiceTotal',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
