# Generated by Django 3.1.4 on 2020-12-30 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_app', '0005_auto_20201230_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='companyAddress',
            new_name='company_address',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='companyCity',
            new_name='company_city',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='companyCountry',
            new_name='company_country',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='companyPostCode',
            new_name='company_post_code',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='paymentAccount',
            new_name='payment_account',
        ),
    ]
