# Generated by Django 3.1.4 on 2021-01-02 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices_app', '0009_auto_20201230_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='auth.user'),
            preserve_default=False,
        ),
    ]
